### ISSUE TITLE
fool

### ISSUE THREAD

**Issue by yongxingzhao** [DBXHLY/DB-code#1]
# **QiQiZhao**, You is bulabulabula................................................
<br>
<h1 align="center">==You is chook==</h1>
![Uploading 13.jpeg…]()

**Comment by YongXingZhao** [comment]
> # **QiQiZhao**, You is bulabulabula................................................
> 
> # ==You is chook==
> ![Uploading 13.jpeg…]()



> # **QiQiZhao**, You is bulabulabula................................................
> 
> # ==You is chook==
> ![Uploading 13.jpeg…]()

**Comment by DBXHLY** [comment]
you are good boy
